### ISSUE TITLE
pages:document-link creates duplicate element on url with hash

### ISSUE THREAD

**Issue by line-o** [HistoryAtState/hsg-shell#139]
Compare the breadcrumb when no hash is in the URL:
http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775

with the output here when the hash sign is in the URL:
http://localhost:8080/exist/apps/hsg-shell/milestones/1750-1775#

**Comment by joewiz** [comment]
I see no difference when loading these URLs now.
