### ISSUE TITLE
Bad link to countries/issues

### ISSUE THREAD

**Issue by wolfgangmm** [HistoryAtState/hsg-shell#184]
The entry on Baden http://localhost:8000/exist/apps/hsg-shell/countries/baden (my home country ;-) links to

http://localhost:8000/exist/apps/hsg-shell/countries/issues/german-unification

but this page does not exist.

**Comment by joewiz** [comment]
As noted in https://github.com/eXistSolutions/hsg-shell/issues/150#issuecomment-203481274. The `countries/issues` pages are stored in https://github.com/HistoryAtState/rdcr/tree/master/issues - and in hsg-project, the data is stored in `/db/apps/rdcr/issues`.

**Comment by joewiz** [comment]
The pages that should be visible after completing this are:

- /countries/issues
- /countries/issues/china-us-relations
- /countries/issues/german-unification
- /countries/issues/italian-unification

**Comment by plutonik-a** [comment]
@wolfgangmm /cc @tuurma I am still blocked with this issue and commented on the problem here: https://trello.com/c/3osTGJQR
