### ISSUE TITLE
[frus-history] Image path is wrong

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#195]
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/amateurs-need-not-apply](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/amateurs-need-not-apply)
[https://history.state.gov/beta/historicaldocuments/frus-history/research/amateurs-need-not-apply](https://history.state.gov/beta/historicaldocuments/frus-history/research/amateurs-need-not-apply)

<img width="689" alt="missing-image" src="https://cloud.githubusercontent.com/assets/1157669/14747145/1769b242-08b3-11e6-8cd6-c09081d48d58.png">

**Current wrong path:**
`src="//s3.amazonaws.com/static.history.state.gov//adee-alvey-a.png"`

**Correct path:**
[https://s3.amazonaws.com/static.history.state.gov/frus150/adee-alvey-a.png](https://s3.amazonaws.com/static.history.state.gov/frus150/adee-alvey-a.png)

---

All images in pages `historicaldocuments/frus-history/research/*` have an incorrect path.

**Comment by plutonik-a** [comment]
**My findings so far:**

File `resources/odd/compiled/frus-web.xql` ->  in `model:apply()`
```
case element(graphic) return
    html:graphic($config, ., ("tei-graphic"), ., xs:anyURI('//s3.amazonaws.com/static.history.state.gov/' ||
    $parameters?base-uri ||  "/"  || @url  || (if (matches(@url, "^.*\.(jpg|png|gif)$")) then "" else ".png")), (), (), @scale, desc)
```

The sourcefile [frus-history/articles/amateurs-need-not-apply.xml](frus-history/articles/amateurs-need-not-apply.xml):
`<graphic url="adee-alvey-a.png"/>`

So, the `$parameters?base-uri `  was not set to `frus150` like in the original path above. 
**How or where can I set it?**

**Comment by plutonik-a** [comment]
When I try to correct the URL for graphics (`ident="graphic"`) in `resources/odd/source/frus.odd` for `historicaldocuments` graphics, the URLs for graphics in `departmenthistory` change as well, even though those graphic URLs should be processed by the equivalent model in `resources/odd/source/departmenthistory.odd`. 
And an URL change in the latter file doesn't have any effect whatsoever.
That is very strange! 

Tested pages:
Historicaldocuments
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/frus-at-war](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/research/frus-at-war)

Departmenthistory
[http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/seward-william-henry](http://localhost:8080/exist/apps/hsg-shell/departmenthistory/people/seward-william-henry)

**Comment by joewiz** [comment]
I think this is a question best answered by @wolfgangmm or @tuurma, since it's at the ODD and TEI PM level. See the question above about `$parameters?base-uri`.

**Comment by joewiz** [comment]
This issue appears to be fixed, as the images on the referenced pages show up correctly.
