### ISSUE TITLE
[frus] Person's sidebar: Different content in tooltips 

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#238]
The description in the tooltips when hovering names in the person's sidebar shows different content, depending on the markup of its source file:

[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v07p1/d13](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1952-54v07p1/d13)
```xml
<item>
    <hi rend="strong">
        <persName xml:id="p_AK1">Adenauer, Konrad</persName>
    </hi>, Chancellor of the Federal Republic of Germany and, from March 1951, Minister of Foreign Affairs.
</item>
```
is rendered with unwanted fullstop and comma as

<img width="297" alt="bildschirmfoto 2016-06-13 um 12 47 54" src="https://cloud.githubusercontent.com/assets/1157669/16004988/1a15fe58-3165-11e6-86ce-290bb4e62cae.png">

---

[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1955-57v15/d159](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1955-57v15/d159)
```xml
<item>
    <hi rend="strong">
        <persName xml:id="p_ARB1">Anderson, Robert B.</persName>,
    </hi> Deputy Secretary of Defense ...
</item>
```
is rendered as

<img width="299" alt="bildschirmfoto 2016-06-13 um 12 47 00" src="https://cloud.githubusercontent.com/assets/1157669/16004971/ff500960-3164-11e6-87c6-c4a7c7596870.png">

---

#### File
`modules/frus-html.xqm`
[https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-html.xqm#L315](https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-html.xqm#L315)

**Comment by plutonik-a** [comment]
I've made a hotfix for this problem.
Result so far:

<img width="299" alt="bildschirmfoto 2016-06-13 um 15 17 01" src="https://cloud.githubusercontent.com/assets/1157669/16008989/fe01729a-317a-11e6-8651-8172f16c0315.png">

But, I am working on filtering all unwanted characters from the description.

**Comment by joewiz** [comment]
We can obtain a sample of each volumes' Lists of Persons using the following query:

```xquery
xquery version "3.0";

declare namespace tei="http://www.tei-c.org/ns/1.0";

element samples {
    for $vol in collection('/db/apps/frus/volumes')
    return
        element sample {
            attribute vol-id { util:document-name($vol) },
            ($vol//tei:persName[@xml:id])[1]/ancestor::tei:item[1]/node()
        }
}
```

Here are the representative variants:

1. No markup between `<persName>` and description
```
<persName xml:id="p_HA1">Abbas Hilmi</persName>, Khedive of Egypt.
<persName xml:id="p_ADG1"><hi rend="smallcaps">Acheson</hi>, Dean G.</persName>, Assistant Secretary of State.
```
2. `<persName>` wrapped in `<hi>`
```
<hi rend="strong"><persName xml:id="p_BND_1">Baker, Newton Diehl</persName>,</hi> Secretary of War from 1916 until 1921
```

Since we want to trim any leading comma in the description, the XPath for obtaining the description from any given `<persName xml:id="...">` in a List of persons is:

```xquery
xquery version "3.0";

declare namespace tei="http://www.tei-c.org/ns/1.0";

for $p in //tei:persName
let $following := 
    if ($p/parent::tei:hi) then
        $p/parent::tei:hi/following-sibling::node() 
    else 
        $p/following-sibling::node() 
return 
    element description { 
        replace(subsequence($following, 1, 1), '^\s*,?\s+', ''),
        subsequence($following, 2)
    }
```

This should provide a basis for deriving the display text for the pop-ups.
