### ISSUE TITLE
AJAX navigation/footnotes broken

### ISSUE THREAD

**Issue by wolfgangmm** [HistoryAtState/hsg-shell#253]
Navigating pages via AJAX is broken again on history.state.gov. I'm not sure why, but it appears app.js is NOT initialized at all. Mouseover on a footnote should also show a pop up.

I'm not sure if this is caused by app.js being uglyfied. I don't understand gulp at all, so I'm somewhat lost debugging this. Please have a look.

See also #248, which points to the same issue with app.js not being loaded properly when deployed in minimized form.

**Comment by plutonik-a** [comment]
@line-o 
I have the same impression, that `app.js` isn't compressed correctly and built into `app.all.js`.
Can you please have a look, what might be the cause? 
The [gulp task](https://github.com/HistoryAtState/hsg-shell/blob/master/gulpfile.js#L95-L108) is looking correct.
On the other hand, it did work before...

**Comment by line-o** [comment]
@wolfgangmm @joewiz @tasmo Which version of node is in use on the production machines?

**Comment by tasmo** [comment]
@line-o node v4.6.0
