### ISSUE TITLE
Table overflowing width of parent div

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#256]
As reported by Josh Botts:

> Wanted to report what looks like a rendering error on the website. To respond to a mailbox inquiry, I ended up navigating to the White House log of the Roosevelt’s participation in the Tehran conference that was published in FRUS - at https://history.state.gov/historicaldocuments/frus1943CairoTehran/d353. As you can see in the screenshot below, the text is cut off.
>
> <img width="954" alt="screen shot 2016-11-16 at 9 25 24 am" src="https://cloud.githubusercontent.com/assets/59118/20350901/a51c7812-abde-11e6-839e-48c3f7bb6394.png">

I can confirm the bug. 

@plutonik-a Is there a way to constrain the width of the table?

**Comment by plutonik-a** [comment]
@joewiz 
I've found inline styles in the code, which seem to interfere with the table layout.

<img width="379" alt="bildschirmfoto 2016-11-16 um 16 26 48" src="https://cloud.githubusercontent.com/assets/1157669/20353705/0494a872-ac1c-11e6-8bed-f8b5a69610ed.png">

I wasn't able to find these inline styles in the current hsg-shell templates or frus documents.
Have you got a clue about this?

**Comment by joewiz** [comment]
@plutonik-a Thank you for spotting this. These are inserted as TEI "rendition" values:

```xml
<table rows="74" cols="2">
    <row>
        <cell rendition="#top #nowrap"><hi rend="italic">5:58 a.m.</hi></cell>
        <cell>The President and members of his party left his villa for the
            airport. All hands were up and ready for a 4:30 a.m. departure
            for the airport but word had been received that our take-off
            would have to be delayed temporarily due to fog over the
            field.</cell>
    </row>
    <!-- snip -->
</table>
```

These values are defined in the TEI Header. Our typical block is like this:

```xml
<TEI xmlns="http://www.tei-c.org/ns/1.0">
    <teiHeader>
        <encodingDesc>
            <styleDefDecl scheme="css" schemeVersion="2.1"/>
            <tagsDecl>
                <rendition xml:id="top">vertical-align: top;</rendition>
                <rendition xml:id="bottom">vertical-align: bottom;</rendition>
                <rendition xml:id="middle">vertical-align: middle;</rendition>
                <rendition xml:id="nowrap">white-space: nowrap !important;</rendition>
                <rendition xml:id="nopad">padding-right: 0.5em !important;</rendition>
                <rendition xml:id="border-top">border-top: 1px black solid;</rendition>
                <rendition xml:id="border-bottom">border-bottom: 1px black solid;</rendition>
                <rendition xml:id="border-left">border-left: 1px black solid;</rendition>
                <rendition xml:id="border-right">border-right: 1px black solid;</rendition>
                <rendition xml:id="center">display: block; text-align: center;</rendition>
                <rendition xml:id="center-block">margin-left: auto; margin-right: auto;</rendition>
                <rendition xml:id="underline">text-decoration: underline;</rendition>
                <rendition xml:id="hanging">padding-left:1.5em; text-indent:-1.5em;</rendition>
                <rendition xml:id="left">display: inline; float: left;</rendition>
                <rendition xml:id="right">display: inline; float: right;</rendition>
            </tagsDecl>
            <!-- snip -->
```

So the inserted styles are correct and as we anticipated, but what I didn't expect was that applying the `white-space` and `vertical-align` properties to cells in the left column would somehow cause the cells in the right column to inherit these same properties. I must be misunderstanding something about CSS. Our goal is to prevent line wrap in the left column, while allowing it in the right column.

Do you have any idea how to achieve this?  We can certainly change the CSS directives in the rendition block or alter our approach.

**Comment by joewiz** [comment]
Could a single cell with the `white-space` property cause this property to apply to the entire column?  I do see some cells in the 2nd column with the `white-space` property set.  XPath in oXygen: `//cell[2][contains(@rendition, 'wrap')]`

**Comment by plutonik-a** [comment]
@joewiz 
>  I do see some cells in the 2nd column with the white-space property set.

You were right with this. It seems to be a mistake, that 3 cells of the second column get the class `document_top document_nowrap`.  
I removed the attributes `#top #nowrap` from cells in the 2nd column.

Fixed with commit https://github.com/HistoryAtState/frus/pull/82/commits/0f04973deaa02900fdd6888bfed9451fc5f7f32e in https://github.com/HistoryAtState/frus/pull/82

**Comment by joewiz** [comment]
@plutonik-a Thank you for the fix!

@vak2ve Please note that setting one cell as `#nowrap` affects its entire column (as explained above in this thread).

**Comment by vak2ve** [comment]
@joewiz Understood, looks like a copy-paste error when I was doing the left-hand column--apologies for the mistake!
@plutonik-a Thanks for catching this!
