### ISSUE TITLE
FRUS persons/terms sidebar links do not lead to desired place on page

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#260]
In FRUS persons and terms sidebar links, like those at https://history.state.gov/historicaldocuments/frus1977-80v30/d67, the links should take us to a location of the target page. However, the target page, as currently generated, lack the `@id` anchors for the link. So a sidebar link on this page, like:

  https://history.state.gov/historicaldocuments/frus1977-80v30/persons#p_BWM_1

Takes us only to the top of the "persons" page, since there is no `<item id="p_BWM1">` on the persons page.

I think the solution is to ensure TEI PM outputs elements' original `@xml:id` values as `@id` on HTML elements.

**Comment by tuurma** [comment]
closed with dbca8af700602d6038498a8576ed16579fa8e436
