### ISSUE TITLE
Support static.history.state.gov URLs

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#265]
Since 2011 hsg has hosted our static files on Amazon S3, in a bucket called "static.history.state.gov", and we created a domain which would point to the S3 bucket. So requests for http://static.history.state.gov/frus/frus1977-80v01/pdf/frus1977-80v01.pdf would actually hit http://s3.amazonaws.com/static.history.state.gov/frus/frus1977-80v01/pdf/frus1977-80v01.pdf. However, since we began supporting SSL/TLS and especially since enforcing SSL/TLS connections with HSTS last December 31, we switched away from this practice, linking instead directly to s3.amazonaws.com. This is because accessing https://static.history.state.gov/frus/frus1977-80v01/pdf/frus1977-80v01.pdf (notice HTTPS URL) would raise a certificate error - a known issue with S3. Linking directly to s3.amazonaws.com avoids the error.

I had been planning to discontinue use of static.history.state.gov, but I just discovered that quite a few sites and books have linked directly to these URLs. See <https://www.google.com/search?q="static.history.state.gov">. 

Thus I think the responsible approach is to switch our DNS to point to our frontend nginx servers, and have these servers serve as a proxy for the s3 assets. 

@tasmo Could you help with this?

**Comment by tasmo** [comment]
Sure, I can try to be helpful.

> Linking directly to s3.amazonaws.com avoids the error.

...because the Amazon S3 domain is not forced to use TLS.

A redirect within nginx from <static.history.state.gov> to an other URI or a sub directory should be easy. I don't know yet, where to link to.

Do you want to have these links to be enforced to use the secure connection or should the links to frus be unsecured?

**Comment by joewiz** [comment]
Thanks, Thomas! 

> ...because the Amazon S3 domain is not forced to use TLS.

Close. We use HTTPS links to s3.amazonaws.com to avoid "mixed content" warnings (contrast with https://www.state.gov ;), but since S3's servers don't have our SSL certificate for static.history.state.gov, an HTTPS link to the static.history.state.gov domain alias will return certificate errors. Apparently AWS CloudFront lets you upload your certificate, and they'll serve assets from your domain over SSL, but not so for S3.

> A redirect within nginx from <static.history.state.gov> to an other URI or a sub directory should be easy. I don't know yet, where to link to.

Basically nginx should listen for HTTP and HTTPS requests to static.history.state.gov/(.*), and it should reverse proxy the request to `https://s3.amazonaws.com/static.history.state.gov/(.*)`. (We are in the us-east-1 region, which according to http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region can be addressed simply with s3.amazonaws.com.)

> Do you want to have these links to be enforced to use the secure connection or should the links to frus be unsecured?

We should redirect HTTP requests to HTTPS and add the `Strict-Transport-Security` header (set to one year, as for the hsg (sub-)domains. 

Also, since we never had an SSL certificate for `static.hsg`, could you please generate one with Let's Encrypt? 

In terms of DNS, I'll request that the entry for `static.history.state.gov` be updated to the hsg load balancer. Do you agree that I should point it to the load balancer and not to a specific server/elastic IP?

**Comment by tasmo** [comment]
> Also, since we never had an SSL certificate for `static.hsg`, could you please generate one with Let's Encrypt?

We can do so. That for we can stop 1861 for the certbot to get the Let's Encrypt cert and afterwards for 1991 as well. 

> In terms of DNS, I'll request that the entry for `static.history.state.gov` be updated to the hsg load balancer. Do you agree that I should point it to the load balancer and not to a specific server/elastic IP?

I don't see any difficulties right now.

**Comment by joewiz** [comment]
@tasmo Two updates: I am finally submitting this request to the DNS team to move the `static` domain to the hsg load balancer. I see you've added initial nginx support for receiving these requests and proxying them to the s3 server (namely, https://github.com/HistoryAtState/hsg-project/blob/master/deploy/1861/etc/nginx/vhosts/static.hsg.conf and its equivalent for 1991). Could you confirm the following:

- [ ] Will nginx automatically include the HSTS headers when it serves up proxied resources from s3? 
- [ ] Will nginx redirect any HTTP requests to HTTPS with 301 responses?

If either isn't in place yet, could you please work on adding them?

Also, could you please add the following, to support my other DNS request to point `www.history.state.gov` to our load balancer:

- [ ] Accept requests for `www.history.state.gov` and redirect them to `history.state.gov` (again, using HSTS response headers and 301s to upgrade any HTTP requests to HTTPS)

Lastly, will supporting requests for these domains require SSL certs? If so: 

- [ ] Could you please configure letsencrypt to generate certs for them?

I'll update this issue as I hear back from the DNS team about when they are able to make the switch. Once the DNS changes have been made, I'd hope, if possible, to be able to test your implementation and confirm that all functionality is in place within ~1 week or so.

**Comment by tasmo** [comment]
@joewiz For static I had to add the HSTS header (https://github.com/HistoryAtState/hsg-project/commit/262ec507bed437bec66f5351527a535cda710566), HTTP redirects now to HTTPS (https://github.com/HistoryAtState/hsg-project/commit/e8606b5f8437a1841305a47a7c6a138caf49c448) and redirection and Let's Encrypt is ready for www (https://github.com/HistoryAtState/hsg-project/commit/731aba1eee4c0a33319607d6b4db1c6e5b1a7ff2).

**Comment by tasmo** [comment]
@joewiz Is this issue still opened or can it be closed?

**Comment by joewiz** [comment]
@tasmo Oh, this can definitely be closed. The new setup has been working perfectly. Thanks again!
