### ISSUE TITLE
"Search within volume(s)" parameters are dropped when submitting a new search

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#269]
Steps to reproduce:

1. Starting from a volume's landing page (e.g., https://history.state.gov/historicaldocuments/frus1964-68v18), enter a search into the right sidebar's "Search inside this volume" field (e.g., `jerusalem`), and submit the search.

2. The resulting page is https://history.state.gov/search?q=jerusalem&volume-id=frus1964-68v18. Click on submit to re-do the same search.

3. The resulting page is https://history.state.gov/search?q=jerusalem&within=on. Notice how the `volume-id` parameter has changed to a `within` parameter, and there are no search results. It seems the volume-id parameter isn't being passed as a search parameter from the https://history.state.gov/search page.

Similarly, you can start from https://history.state.gov/search/select-volumes, enter a search term, select 1+ volumes, and submit to see results — but from the results page, hitting submit results in the same problem where any `volume-id` parameters are replaced by a `within` parameter.

Reported by James Wilson.

**Comment by tuurma** [comment]
with newly installed hsg-project I get this error when searching within volume, eg. http://localhost:8080/exist/apps/hsg-shell/search?q=ambassador&volume-id=frus1981-88v06

![image](https://cloud.githubusercontent.com/assets/449468/26203796/89e7db96-3bd4-11e7-802d-d12837cb823b.png)

**Comment by tuurma** [comment]
sorry for the noise, I've pulled in the latest hsg-shell and rebuilt, my strange error is gone
