### ISSUE TITLE
Homepage tweets - duplicated text

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#270]
The following tweet (see original at https://twitter.com/EEOCNews/status/834137356043182084) has duplicated text on hsg:

> ![screen shot 2017-02-22 at 1 35 40 pm](https://cloud.githubusercontent.com/assets/59118/23226539/e529417a-f903-11e6-862e-5c2f31a1182e.png)

**Comment by plutonik-a** [comment]
This obviously only happening if the tweet is contains a cite. Then the duplication of the post is triggered.

https://twitter.com/StateDept/status/857699308451266560

<img width="584" alt="bildschirmfoto 2017-05-15 um 18 21 00" src="https://cloud.githubusercontent.com/assets/1157669/26068118/b791c848-399c-11e7-9b11-8cdb330fc637.png">

rendered as 

<img width="289" alt="bildschirmfoto 2017-05-15 um 18 20 43" src="https://cloud.githubusercontent.com/assets/1157669/26068110/b062deae-399c-11e7-87af-bdded586421d.png">

**Comment by joewiz** [comment]
I was just looking at this again myself, in fact - thanks to the prominent mangled tweet on the homepage! I've tracked down the issue in the code to https://github.com/HistoryAtState/twitter/blob/master/modules/process-tweets.xqm#L167-L180. I'll need to make sure that the original workaround there for long tweets doesn't regress with my fix.

**Comment by plutonik-a** [comment]
This issue seems to be fixed.
