### ISSUE TITLE
Issues resulting in broken back button behavior

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#273]
As reported by James Wilson, and confirmed by me, we have some buggy behavior involving ajax requests and the back button.

Steps to reproduce:

1. Go to https://history.state.gov/historicaldocuments/frus1981-88v06/comp1?start=91
2. Select the link to Document 93, advancing (via ajax request) to https://history.state.gov/historicaldocuments/frus1981-88v06/d93
3. Click the browser's back button. Instead of returning to `comp1?start=91`, the URL bar and page loaded is the `d93` page again.
4. Click the browser's back button. While the URL bar says `comp1?start=91`, the page loaded is the `comp1` page, starting with Document 1 instead of Document 93.

With Chrome's developer pane > Network, the actual requests made for the actions 2-4 above are:

2. https://history.state.gov/modules/frus-ajax.xql?url=%2Fhistoricaldocuments%2Ffrus1981-88v06%2Fd93. This URL is requested **twice**!
3. https://history.state.gov/modules/frus-ajax.xql?url=%2Fhistoricaldocuments%2Ffrus1981-88v06%2Fd93
4. https://history.state.gov/modules/frus-ajax.xql?url=%2Fhistoricaldocuments%2Ffrus1981-88v06%2Fcomp1

So the questions to solve here are:

1. Why does clicking on document 93 in step 2 above result in two HTTP requests being made? Fixing this would fix the initial back button problem in step 3.
2. Why is the `?start=91` parameter dropped from the ajax request in step 4?

**Comment by tuurma** [comment]
Furthermore, starting from https://history.state.gov/historicaldocuments/frus1981-88v06/comp1?start=91 clicking the ajax navigation arrows for next page > the page loaded is again https://history.state.gov/historicaldocuments/frus1981-88v06/d1 (Document 1) while arrow for previous page goes to https://history.state.gov/historicaldocuments/frus1981-88v06/abouttheseries

**Comment by joewiz** [comment]
@tuurma Thanks for identifying a workaround. Is there anyone who can help with a thorough fix to this issue — i.e., a fix that would restore the ajax functionality?

**Comment by joewiz** [comment]
After discussing this with @tuurma and @wolfgangmm just now, we decided that the benefit of restoring ajax to TOC-based links is marginal and that Magdalena's workaround is adequate. We will drop ajax functionality from TOC-based links. This leaves ajax to prev/next navigation. Thanks for getting to the bottom of this, Magdalena!
