### ISSUE TITLE
Create component "filter by section"

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#286]
* Toggle between entire search or selected sections:
    a. Option "Entire Office of The Historian Website"
    b. Option Group with all Website Sections as a list
* Selecting option a selects also all options b.
* Deselecting option a leaves all options b selected.
* Single options in b can be deselected. 
* If the last item of option b is deselected, all options a and b will be selected entirely.
* If the section "Historical Documents" is selected, show the filter component "Filter By Date".

**Component in search page:**
<img width="382" alt="bildschirmfoto 2017-11-10 um 15 27 17" src="https://user-images.githubusercontent.com/1157669/32662687-b0d1df2c-c62b-11e7-8dd4-aff5bb344bb2.png">

**Component in results page:**
![bildschirmfoto 2017-11-13 um 13 12 50](https://user-images.githubusercontent.com/1157669/32725204-7bb366da-c874-11e7-96fa-d872e8af7b6e.png)

---

**Update:** from https://github.com/HistoryAtState/hsg-shell/issues/284#issuecomment-343969089
* Text-color should be default text-color instead of link-color
* Display amount of hits next to the option (on the results page)
* "More Sections" instead of "Show more"

---

URL: https://history.state.gov/search
Template: `pages/search/index.html`
Parent: https://github.com/HistoryAtState/hsg-shell/issues/284
Dependent on: https://github.com/HistoryAtState/hsg-shell/issues/287

**Comment by joewiz** [comment]
Regarding this point:

> If the section "Historical Documents" is selected, show the filter component "Filter By Date".

We hope it's possible to "gray out" the "Filter By Date" component, rather than hide it.

**Comment by plutonik-a** [comment]
**Landing Page**
<img width="971" alt="bildschirmfoto 2017-11-20 um 16 56 09" src="https://user-images.githubusercontent.com/1157669/33027608-dc637534-ce13-11e7-9c29-220508a868e9.png">

**Result Page**
<img width="319" alt="bildschirmfoto 2017-11-20 um 16 56 32" src="https://user-images.githubusercontent.com/1157669/33027600-d6174908-ce13-11e7-9693-9c51965b9614.png">

**Comment by plutonik-a** [comment]
Update: Changed the layout according to https://standards.usa.gov/components/form-controls/#checkboxes 
and fixed the logic of selecting and deselecting the checkbox options.

<img width="406" alt="bildschirmfoto 2017-11-23 um 17 49 55" src="https://user-images.githubusercontent.com/1157669/33183109-d69c296a-d076-11e7-8e3c-2719bd338a59.png">

<img width="394" alt="bildschirmfoto 2017-11-23 um 17 50 03" src="https://user-images.githubusercontent.com/1157669/33183117-dc7cf99a-d076-11e7-8b67-26d2a25a20da.png">

**Comment by tuurma** [comment]
Looks like we're done here, we'll test it a bit more and then close if everything's okay

**Comment by tuurma** [comment]
Looks like I had some hiccups with my local instance yesterday. Closing.
