### ISSUE TITLE
Create component "Filter Sidebar"

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#287]
If search results are displayed, show filters in a sidebar on the left next to the results on large screens, up to the media break point for medium sized screens, display filters in a row before the results list.
Create a "Reset all filters" button below all filters, that will reset all contained filters to the initial default state.

**Update:**
> make the text-color of checkbox items the default text-color, not the blue color of links.

> Please replace the "show more" link with contextual labels: "More Sections", "More Administrations", "More Volumes". We will define these for each filter grouping.

> Please include a right-aligned count of items, referencing the loc.gov screenshot. Sample text and code for deriving the item count can be found above in #284 (comment). Since we may not implement item counts in time for the December release, please include a class and placeholder element for this that we can populate.

> In the "Filter by", please add a "+/-" toggle to expand/collapse for each grouping (e.g., Sections, Date, Administration, Volumes, etc.), right-aligned. This should replace the "v" icon shown next to the Date filter toggle.
For reference, please see the left sidebar in https://www.loc.gov/search/?q=russia

from https://github.com/HistoryAtState/hsg-shell/issues/284#issuecomment-343969089

<img width="183" alt="bildschirmfoto 2017-11-13 um 13 33 28" src="https://user-images.githubusercontent.com/1157669/32725916-4ab35efc-c877-11e7-8ab9-aba8785cbc8f.png">

---

Related:
https://github.com/HistoryAtState/hsg-shell/issues/286

**Comment by plutonik-a** [comment]
@tuurma @joewiz 

**Status:** 
* The filter sidebar markup & styling is mainly ready. 
   <img width="261" alt="bildschirmfoto 2017-11-16 um 17 33 42" src="https://user-images.githubusercontent.com/1157669/32903077-5c224c00-caf4-11e7-890f-197060e3c832.png">
* Filters "administrations" and "sections" are implemented as placeholders.
* Parameters of clicked filters are serialized as url parameters.
  <img width="798" alt="bildschirmfoto 2017-11-16 um 17 18 03" src="https://user-images.githubusercontent.com/1157669/32902943-0bd2a394-caf4-11e7-99d8-a62e257c8234.png">
* Both search buttons (search bar and main button) trigger the search with filters



**TODO:**
* Collapse and expand filter options
* Replace contents of "sections" with new component #286 when ready
* Add contents of components "date" and "volumes" to sidebar (needs fix of #293 and #288 )
* Filter search results with given parameters

**Comment by tuurma** [comment]
This is ready, I think? Great job @plutonik-a, please close if you're done here.

**Comment by plutonik-a** [comment]
@tuurma No, not done yet. The reset button needs a fix. I'm on it today. And collapsing the checkboxes up to three remaining options per components is also still open for a final decision, as you just posted in #293. I will open an issue for that with an estimation.
