### ISSUE TITLE
Create component "Filter by Date"

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#288]
When section "Historical Documents" is selected, the component "filter by date" will show text inputs for typing a start and an end date, as well as a start time and an end time. All options are optional.

There is no default date or time. Inputs only display a placeholder with the required format.
mm dd yyy // hh mm

**Component on search page:**
<img width="511" alt="bildschirmfoto 2017-11-13 um 13 37 53" src="https://user-images.githubusercontent.com/1157669/32726085-ee106ee6-c877-11e7-9b28-b07d472ee725.png">

**Component in sidebar:**
<img width="367" alt="bildschirmfoto 2017-11-13 um 13 32 44" src="https://user-images.githubusercontent.com/1157669/32725888-2e87b05c-c877-11e7-9387-aee17108bc99.png">

---

Parent: #284 
Dependent on: #287

**Comment by joewiz** [comment]
Just one request, moved here from https://github.com/HistoryAtState/hsg-shell/issues/284#issuecomment-343969089: 

- Please place the "For example" examples beneath all date and time fields (namely, Start Date, End Date, Start Time, and End Time).

**Comment by plutonik-a** [comment]
Status so far: UI is ready
TODO: Correct serialization of input parameters, best as merged group-wise.

**Hidden:**
<img width="957" alt="bildschirmfoto 2017-11-27 um 15 40 46" src="https://user-images.githubusercontent.com/1157669/33272254-e118801c-d389-11e7-8f65-bdceb25f3c7f.png">


**Active:**
<img width="720" alt="bildschirmfoto 2017-11-27 um 15 41 29" src="https://user-images.githubusercontent.com/1157669/33272237-d65f1c26-d389-11e7-9a3b-e0620ca3da30.png">

**Comment by tuurma** [comment]
ideally we want the date controls aggregated for the query string and filter badges but for the time being we will proceed with split-up-controls and join them on the backend

**Comment by tuurma** [comment]
other related commits 
e4ef5370815bbe9d0fc6ebaf04773f81f96c4bc6
749fd9cf9e58c63b6b00b24f3c45e5f65693c1e2
1a15fd0b00f81342f4186225a1e74c702c2e7eed
6590eaa0afe67b421ba44ecd818b07c5fd9d9ae1
f63f241f22e23568d7d3556dd7ea2df97ae8dfe9
fef81e8ca689f5340c291fd5d1bb5d069f773992
b04001d4333a2ecca2ff1580bbc16df6fa7312c1
