### ISSUE TITLE
Create button "Sort by ..."

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#290]
Text next to the button is:
"Sort Results By"

Sort options for the results in the dropdown button are:
1. Relevance - default
2. Dates (oldest first)
3. Dates (most recent first)

<img width="958" alt="bildschirmfoto 2017-11-13 um 13 50 30" src="https://user-images.githubusercontent.com/1157669/32726883-dda9367a-c87a-11e7-80b8-b70826c697d5.png">

---

Parent: https://github.com/HistoryAtState/hsg-shell/issues/284

**Comment by plutonik-a** [comment]
Status:
UI is ready, parameters needs further fixes for serialization.

<img width="1021" alt="bildschirmfoto 2017-11-28 um 16 15 30" src="https://user-images.githubusercontent.com/1157669/33329534-12daf6a6-d45d-11e7-8392-83a7ff5fb442.png">

<img width="222" alt="bildschirmfoto 2017-11-28 um 16 15 41" src="https://user-images.githubusercontent.com/1157669/33329542-18896fb0-d45d-11e7-9596-0a6b548ba3d2.png">

**Comment by joewiz** [comment]
Back end is now prepared for this control to become active, with https://github.com/HistoryAtState/hsg-shell/commit/c929b55e3d97b32eb06c6a3f34c8803c7114f707 and https://github.com/HistoryAtState/hsg-shell/commit/25b3ee219d3f7465a7cd68aa4aabb7468bf2c404.

Compare:

- <http://localhost:8080/exist/apps/hsg-shell/search?q=taiwan&within=documents&start_date=1969-01-01&end_date=1970-01-01>
- <http://localhost:8080/exist/apps/hsg-shell/search?q=taiwan&within=documents&start_date=1969-01-01&end_date=1970-01-01&sort-by=date_asc>
- <http://localhost:8080/exist/apps/hsg-shell/search?q=taiwan&within=documents&start_date=1969-01-01&end_date=1970-01-01&sort-by=date_desc>

**Comment by tuurma** [comment]
completed with a08041a31a8c1d935b11190ddd1a1c24c0df2ac9 and c8f39d9bcf461fe4c9127dc9c98f512518d44479
