### ISSUE TITLE
[Search] Update search bar layout

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#295]
Delete current placeholder, add https://standards.usa.gov/components/search-bar/ styling with a search icon.

<img width="722" alt="bildschirmfoto 2017-11-13 um 14 41 12" src="https://user-images.githubusercontent.com/1157669/32728725-b7ee0f4e-c881-11e7-867a-c3375a588a79.png">

Parent: #284 
Related: https://github.com/HistoryAtState/hsg-shell/issues/294

**Comment by joewiz** [comment]
Please replace the magnifying glass icon with "Search" in the keyword search input field, as this instance appears to fall into the "medium" or "large" category in the https://standards.usa.gov/components/search-bar/ guidelines.

**Comment by plutonik-a** [comment]
<img width="1001" alt="bildschirmfoto 2017-11-13 um 18 12 07" src="https://user-images.githubusercontent.com/1157669/32739030-012d301e-c89f-11e7-83a3-1ed2ec2f733e.png">


<img width="313" alt="bildschirmfoto 2017-11-13 um 18 16 33" src="https://user-images.githubusercontent.com/1157669/32739017-fb1e04d2-c89e-11e7-865a-98004ecf3a81.png">
