### ISSUE TITLE
[search] return key should submit the form

### ISSUE THREAD

**Issue by tuurma** [HistoryAtState/hsg-shell#301]

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/commit/86e87dbad779aadf757cb2012629295ec170292b

**Comment by joewiz** [comment]
I get this error when hitting "return" from any of the date fields (using macOS 10.13.1 with Chrome 62.0.3202.94):

```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at submitSearch (app.js:125)
    at HTMLDocument.document.onkeydown (app.js:188)
submitSearch @ app.js:125
document.onkeydown @ app.js:188
```

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/commit/3f2c41ac2b62f57173610593a819dfb0bd500d5b

**Comment by joewiz** [comment]
@plutonik-a Thanks! I can confirm this is working now.
