### ISSUE TITLE
Date-only search should be possible

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#303]
If a date is selected, but no keywords are entered, submitting the search form returns to the search landing page instead of the search results page. A date-only search should still take us to the results page.

**Comment by plutonik-a** [comment]
Related #288

**Comment by joewiz** [comment]
Added date-only search with https://github.com/HistoryAtState/hsg-shell/commit/77fdc55b4f0ec583d6ac679ee9ee88db5cff3394.

**Comment by joewiz** [comment]
Some sample keyword search-less queries

- <http://localhost:8080/exist/apps/hsg-shell/search?within=documents&start_date=1973-08-01&end_date=1973-09-01&sort-by=date_asc>

    > ![screen shot 2017-12-05 at 3 09 29 am](https://user-images.githubusercontent.com/59118/33596500-db82bf56-d969-11e7-980c-ccadba9124c0.png)

- <http://localhost:8080/exist/apps/hsg-shell/search?within=documents&start_date=1973-08-01&end_date=1973-09-01&sort-by=date_desc>

    > ![screen shot 2017-12-05 at 3 09 50 am](https://user-images.githubusercontent.com/59118/33596504-e28cbf54-d969-11e7-83aa-1bc3feec848a.png)
