### ISSUE TITLE
Section filter problems when limiting search to "Historical Documents"

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#304]
A search limited to "Historical Documents" is shown in the results page's "Sections" filter with "Entire Site" checked too, when only the "Historical Documents" checkbox should be checked. For example, this URL <http://localhost:8080/exist/apps/hsg-shell/search?q=taiwan&within=documents&start_date=1969-01-01&end_date=1970-01-01> will result in the following incorrect state of checkboxes:

> ![screen shot 2017-12-03 at 9 05 21 pm](https://user-images.githubusercontent.com/59118/33533230-b1f3ab02-d86d-11e7-812c-f4d123aa32ee.png)

With this state, the dates filter is hidden, until the user manages to un-select "Entire Site" and re-select "Historical Documents."

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/commit/006297a7f368d0f4f5066062301ad882780a3fc5
