### ISSUE TITLE
Any features not being implemented for the dates search release target should be hidden

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#305]
As discussed with Magdalena, these include:

- Badges showing faux item count ("8")
- Exact phrase, case sensitive, punctuation sensitive
- Administrations filter

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/commit/0b84dd6bb0ec349d9978526c90cb3eff1ecabb9c, https://github.com/HistoryAtState/hsg-shell/commit/26b00419fe27837ca3c27d1d3eaa4128b4c3a478 and https://github.com/HistoryAtState/hsg-shell/commit/3db1717dfdfe061f2a22d1b1c213bd084b4e90e7
