### ISSUE TITLE
AM and PM radio buttons can both be selected

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#306]
See:

> ![screen shot 2017-12-04 at 9 50 17 am](https://user-images.githubusercontent.com/59118/33558783-c8b160e4-d8d8-11e7-86e8-6ef1fce4e0d7.png)

I believe this bug was introduced in https://github.com/HistoryAtState/hsg-shell/commit/94feca402278a26132164cf92f21fb1f03763261#diff-469412cd47057d334c17376081b400abR47, when the radio buttons' `input/@name` attributes were changed from a common value, `start_time`, to two different values, `start_time_am` and `start_time_pm`.

**Comment by tuurma** [comment]
e4ef5370815bbe9d0fc6ebaf04773f81f96c4bc6
