### ISSUE TITLE
Parameter serialization problem

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#307]
From the search landing page, entering a keyword like `taiwan` into the search box in the body of the page and submitting the search yields the following URL:

<http://localhost:8080/exist/apps/hsg-shell/search?q=taiwanq=&within=entire_site>

Note that the `q` parameter here is `taiwanq=` instead of `taiwan`.  `q=` is being appended to the parameter.

Each time the search button is hit, an additional `q=` is appended to the `q` parameter.

If on a result pages you enter a new search term into the sitewide search (in the header), the new term is appended to the existing parameter:

<http://localhost:8080/exist/apps/hsg-shell/search?q=taiwanq%3Dq=taiwan&within=entire_site>

(In other words, the string `q=taiwan` is concatenated to the existing `taiwanq=` parameter.)

**Comment by tuurma** [comment]
Thanks @joewiz, we have noticed already and @plutonik-a and @wolfgangmm are trying to fix for a while now.

**Comment by joewiz** [comment]
@tuurma Great, thank you!

**Comment by joewiz** [comment]
Workaround added to https://github.com/HistoryAtState/hsg-shell/commit/3befe3f72d276b3ac3bbd1cc087a83f6e95d590e

**Comment by tuurma** [comment]
we had some further problems detected today and fixed with b44b32759037849f56439f95aedc6700b094dbb9
