### ISSUE TITLE
Ensure sorting of hits is performed before trimming (performance?)

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#313]
Reviewing the logic of `search:load-results`, it appears that the behavior of `search:filter` causes result sets to be trimmed (if the hit count exceeds $search:MAX_HITS_SHOWN) *before* the hits are sorted. Sorting should be performed first, so relevant hits aren't removed from the set. However, the current behavior appears to have been shaped by performance considerations (i.e., preventing bottlenecks), so please investigate the performance implications. Any operations to reduce the size of the result set should happen before the results are sorted into the requested order.

**Comment by joewiz** [comment]
Another manifestation of this issue is that the search summary for http://localhost:8080/exist/apps/hsg-shell/search?q=china, which should have >30,000 hits, says:

> Displaying 1 – 10 of 1000 results (Results returned in 0.743s.)

If I understand `search:message-limited`, if this were working it would say:

> Displaying 1 – 10 of 30,000 results (Display limited to 1000 results)

So this leaves 2 questions:

1. How do we know that the 1,000 shown are the 1,000 most relevant / earliest / latest within the full result set of 30,000?
2. Can the total # of hits be shown?
3. Do we still benefit from trimming the size of the result set to 1,000? I'm not against trimming - people should refine their search rather than paging through thousands of results. Just want to confirm this is the purpose of such a limit.

**Comment by wolfgangmm** [comment]
According to stress tests, performance is pretty bad after applying the changes, but I will now try to improve it again.

**Comment by wolfgangmm** [comment]
If we always sort the full result set, query times are multiplied by factor 4 for queries returning large sets, e.g.: "nuclear bomb" or "indochina war". Sorting by relevance is ok, but sorting by date will get very slow.

Suggested compromise:

* result sets larger than 1000 hits are always sorted by relevance
* sorting by date is only effective for smaller sets
* it is indicated to the user that sorting is switched to relevance

**Comment by joewiz** [comment]
Thanks, Wolfgang. Your changes here aside, it may be worth comparing the performance of this code to what I implemented at https://history.state.gov/exist/apps/frus-dates (source code at https://github.com/joewiz/frus-dates/blob/master/index.xq#L81-L89).  While that page hasn't been formally stress tested, my experience and impression from others is that performance on that page has been very snappy (and it is running on the same busy servers as the rest of the site). For example:

1. Search for a single term `china` 
  a. Sorting by date returns 40,578 documents in 1.1s: https://history.state.gov/exist/apps/frus-dates/?q=china&order-by=date. 
  b. Sorting by relevance returns in .832s: https://history.state.gov/exist/apps/frus-dates/?q=china&order-by=relevance

2. Phrase search for `"nuclear bomb"`
  a. Date sort return 39 docs in 0.461s: 
  b. Relevance sort returns 39 docs in .459s: https://history.state.gov/exist/apps/frus-dates/?q=%22nuclear+bomb%22&order-by=relevance

3. Phrase search for `"indochina war"`
  a. Date sort returns 193 docs in .427s: https://history.state.gov/exist/apps/frus-dates/?q=%22indochina+war%22&order-by=date
  b. Relevance sort returns 193 docs in .462s: https://history.state.gov/exist/apps/frus-dates/?q=%22indochina+war%22&order-by=relevance

I haven't run these same queries on your revised code, Wolfgang, but in principle the times should be the same. The only substantive difference between the "frus-dates" search and the new site-wide code is:

- The site-wide code searches all collections, not just the FRUS collection; but only the FRUS collection has date attributes (namely, the `@frus:doc-dateTime-*` attributes)
- For hits lacking date attribtues, the "frus-dates" page just treats these as "empty" values; the new site-wide search performs an additional relevance sort on these hits; see https://github.com/HistoryAtState/hsg-shell/blob/feat-advanced-search-284/modules/search.xqm#L520-L532. (We could dispense with this sorting of "undated" documents if it would help performance.)

Does your revised code perform similarly?  If so, then these return times seem within the realm of acceptable performance for me, even the 1.1s of the first entry.  One core use case of date-based searching is precisely to perform corpus-wide searches to locate, for example, "the first time phrase A" was used.  This would be impossible if we limit the size of result sets.  

What are you seeing, and if there is a difference in the performance of the current branch, what do you think could be causing it to perform more slowly?

**Comment by wolfgangmm** [comment]
I have not changed the sorting code, but just refactored it. I definitely see a major difference in performance (e.g. 359 vs 1200) if I compare sorting by relevance and date for those queries. I'll see if this could be improved.
