### ISSUE TITLE
On-hover footnote pop-up feature is broken

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#314]
Hovering over footnote 1 at <http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1961-63v01/d210> with a build of `feat-advanced-search-284` does nothing - broken.

The correct behavior is still in operation on at <https://history.state.gov/historicaldocuments/frus1961-63v01/d210>:

> <img width="543" alt="screen shot 2017-12-05 at 10 10 10 pm" src="https://user-images.githubusercontent.com/59118/33642751-6177c8a0-da09-11e7-9fb7-f104107e07ec.png">

**Comment by joewiz** [comment]
Chrome Developer Tools reveals a javascript error on the local build:

```js
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLDocument.<anonymous> (:8080/exist/apps/hsg-shell/resources/scripts/app.js:386)
    at fire (jquery.js:3099)
    at Object.add [as done] (jquery.js:3145)
    at jQuery.fn.init.jQuery.fn.ready (jquery.js:3378)
    at :8080/exist/apps/hsg-shell/resources/scripts/app.js:1
```

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/commit/05bca33331141440bb0204379f671ec78779f16b
