### ISSUE TITLE
URL history is not preserved after common search actions

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#315]
1. Open a new tab
2. Go to <http://localhost:8080/exist/apps/hsg-shell/search>
3. Enter search term "taiwan", hit submit. Resulting page is <http://localhost:8080/exist/apps/hsg-shell/search?q=taiwan&within=entire_site&sort-by=relevance>
4. Hit the back button. You'll return to the new tab instead of <http://localhost:8080/exist/apps/hsg-shell/search>

Could this be related to the javascript problem in #314?

**Comment by joewiz** [comment]
See the same phenomenon when following the steps in #324:

1. Go to volume landing page, e.g., https://history.state.gov/historicaldocuments/frus1952-54v01p1
2. Enter term like "policy" into "Search within this volume" sidebar. 
3. Hit return to submit search
4. Hit the back button.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/pull/331 (https://github.com/HistoryAtState/hsg-shell/commit/6dc309205024471a82b30a80884cde34d1735bd2)
