### ISSUE TITLE
Only show "Show more" toggle when there are enough entries

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#317]
On a page like <http://localhost:8080/exist/apps/hsg-shell/search?q=china&volume-id=frus1932v04&volume-id=frus1941v01&within=documents&sort-by=date_asc>, the Volumes filter contains only 2 entries, but the "Show more/less" toggle still appears. I believe it should only appear if there are 4 or more, correct?

> <img width="299" alt="screen shot 2017-12-05 at 11 39 03 pm" src="https://user-images.githubusercontent.com/59118/33644878-a36157b6-da15-11e7-9784-f2cd69f150c0.png">

**Comment by tuurma** [comment]
@plutonik-a I think it is ready for you to take over and hide the show more button accordingly

**Comment by tuurma** [comment]
http://localhost:8080/exist/apps/hsg-shell/search?q=foo&within=documents&sort-by=relevance

![image](https://user-images.githubusercontent.com/449468/33676503-30198d2c-dab6-11e7-9e4c-5391a10e433a.png)

http://localhost:8080/exist/apps/hsg-shell/search?q=foo&volume-id=frus1919v01&volume-id=frus1926v01&within=documents&sort-by=relevance

![image](https://user-images.githubusercontent.com/449468/33676544-4856c95e-dab6-11e7-807e-6614cff546d1.png)
