### ISSUE TITLE
[Search]: Volume labels in search filter sidebar are trimmed incorrectly

### ISSUE THREAD

**Issue by plutonik-a** [HistoryAtState/hsg-shell#319]
<img width="299" alt="bildschirmfoto 2017-12-06 um 20 17 19" src="https://user-images.githubusercontent.com/1157669/33680770-ef6c9f28-dac2-11e7-8d7e-b60661d6fb75.png">

Where: http://localhost:8080/exist/apps/hsg-shell/search?q=volume&sort-by=relevance

**Comment by tuurma** [comment]
![image](https://user-images.githubusercontent.com/449468/33828209-80362b72-de6b-11e7-89e1-3765c927ac80.png)
