### ISSUE TITLE
Date parameter serialization: allow yyyy, yyyy-mm

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#320]
Our back end code supports searches of year-only and year-month dates, e.g., 1969 (sans month-day) or 1969-01 (sans day) , but the current branch normalizes these values as 1969-NaN-NaN and 1969-01-NaN.  Would it be possible to serialize these as entered, i.e., as 1969 and 1969-01?

Year-only and year-month searches are a core use case for us—which we hadn't articulated here but as indicated by the prose documentation on the frus-dates page.

**Comment by tuurma** [comment]
@joewiz yes, that was the intention, maybe something slipped in, I will work on that again
