### ISSUE TITLE
Reset/apply button consistency

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#321]
Currently, the date filter has a dedicated "reset date" button, but the volumes filter has no dedicated "reset volumes" button - only a global "reset filters" button. The only "apply" button is a global one beneath the volumes filter.

For consistency, we either need

(1) dedicated "reset filter"/"apply filter" button for each filter 

or

(2) remove per-filter buttons, leaving only a pair of global "reset filters" / "apply filters" button (in effect, just delete/hide the "reset date" button, leaving the existing buttons beneath the volumes filter as is.

I'd prefer the former but am open to the latter if it's all that's achievable for this milestone.

**Comment by tuurma** [comment]
Since Alex is on holiday, I may need to settle on 2 for the current iteration. Will try tomorrow.

**Comment by tuurma** [comment]
I run into some CSS troubles trying to add reset/apply buttons so just removed them from dates for the time being.

![image](https://user-images.githubusercontent.com/449468/33767762-71b668b8-dc23-11e7-85a2-7cb08d4388a3.png)
