### ISSUE TITLE
Javascript error with date search with IE11

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#325]
Submitting a search with the date filter fails in Internet Explorer 11 (Edge). Console error:

> SCRIPT438: Object doesn't support property or method 'padStart'
>
> File: app.all.js, Line: 13, Column: 2272

**Comment by joewiz** [comment]
Other IE notes:

- I also tested the page with IE's developer tools and found this error affects IE 9 and 10.
- IE 8 and lower complain about the addEventListener. 
- Percentage of IE users by version over the last 6 months, according to Google Analytics:
  > ![screen shot 2017-12-15 at 12 40 50 pm](https://user-images.githubusercontent.com/59118/34053567-4481f6b0-e195-11e7-9028-cbfb9c702024.png)
  Based on this, if we can support IE 9-11, we're covering >95% of IE users who visit our site. IE users comprise ~3% of our visitors, but a disproportionate number will probably be those in DOS or other U.S. Federal Gov agencies who use IE as the default browsers. Edge users aren't included in the chart above, so here are the stats by browser (trimmed to just those browsers with >10K hits in the last 6 months):
  > ![screen shot 2017-12-15 at 12 43 28 pm](https://user-images.githubusercontent.com/59118/34053707-d257596c-e195-11e7-94c8-1cabd6ef0a7c.png)

**Comment by tuurma** [comment]
Thanks @joewiz, @plutonik-a was actually asking recently for guidelines
what kind of browser compatibility we are aiming at

**Comment by joewiz** [comment]
@tuurma Ah, good. Thanks in advance!

**Comment by joewiz** [comment]
@tuurma @plutonik-a Hmm, I just received an email from another IE user asking why their date searches aren't working. I confirmed again with IE 11 that the report is valid. The test is to select Historical Documents, enter 04 08 1952, and hit Search. Nothing happens. IE Developer Toolbar's Console notes the same padStart error reported when I submitted this high priority issue... 1.5 months ago now :(. Could you please help us fix this bug?

**Comment by joewiz** [comment]
@tuurma @plutonik-a We now have a report of the same error causing the date search page not working - but this time it's Chrome! The user who reported it happens to be running Chrome 50, released in April 2016. Chrome didn't gain support for `padStart` until Chrome 57, released March 2017. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart for browser compatibility and for the polyfill function required to provide support for browsers that don't support padStart. Here's a screenshot of the user's Console:

> ![unnamed](https://user-images.githubusercontent.com/59118/35946568-51528284-0c32-11e8-976c-5b53c265de8e.png)

**Comment by joewiz** [comment]
@tuurma @plutonik-a Could you provide an update on this request?

**Comment by tuurma** [comment]
As reported by @joewiz when testing this PR

>We're seeing a strange phenomenon, wherein an extra "?" is being appended to the query string. Here are the steps to reproduce (in IE and Chrome on Windows, and on Chrome on macOS)

1. Go to https://history.state.gov/search
2. Enter keyword: Galvao
3. Select Historical Documents filter
4. Enter start date 01 01 1960 and end date 12 30 1968
5. Select the "Search" button beneath the date filter
[5:01 PM] Joe Wicentowski: The resulting URL is https://history.state.gov/search??q=galvao&within=documents&start-date=1960-01-01&end-da... - notice "search??q" instead of "search?q".

This additional ? somehow throws off the date search, causing the query to report 24,507 hits instead of 6.

**Comment by joewiz** [comment]
Closed by #328
